{
  imports = [
    ./adguard.nix
    ./jellyfin.nix
    ./audiobookshelf.nix
    ./samba.nix
    ./headscale.nix
    ./duckdns.nix
    ./wireguard-netns.nix
    ./qbittorrent.nix
    ./prowlarr.nix
    ./sonarr.nix
    ./radarr.nix
    ./jellyseerr.nix
    ./vaultwarden.nix
    ./navidrome.nix
    ./filebrowser.nix
    ./homepage.nix
    ./uptime-kuma.nix
  ];
}
